mod artifacts;
mod build_groups;
mod buildroot_policy;
mod checkpoints;
mod core;
mod diagnostics;
mod image;
mod image_assembly;
mod image_assembly_collected;
mod image_assembly_layout;
mod image_assembly_order;
mod inputs;
mod install_stage;
mod java_policy;
mod model;
mod providers;
mod reporting;
mod sources;
mod workspace;

pub use core::validate_spec;
pub use model::{DiagnosticSeverity, ValidationDiagnostic, ValidationReport};
pub use providers::validate_spec_with_providers;
