//! Git source lockfile (`<build>.gaia.lock`).
//!
//! The lockfile sits next to the build entrypoint and records the commit each
//! git source resolved to, keyed by source id, repository and ref selector.
//! When an entry matches the configured source, resolution sets
//! `GitSourceSpec::locked_commit` so materialization checks out that exact
//! commit. Without a lockfile, sources behave as before.

use gaia_spec::{GitSourceSpec, ResolvedBuildSpec, SourceDefinition};
use serde::Deserialize;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

pub const LOCKFILE_VERSION: u32 = 1;
pub const LOCKFILE_SUFFIX: &str = ".gaia.lock";

#[derive(Debug, Clone, Default, PartialEq, Eq, Deserialize)]
pub struct GitLockfile {
    #[serde(default = "default_version")]
    pub version: u32,
    #[serde(default)]
    pub git: Vec<GitLockEntry>,
}

fn default_version() -> u32 {
    LOCKFILE_VERSION
}

#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
pub struct GitLockEntry {
    pub source: String,
    pub repo: String,
    #[serde(rename = "ref")]
    pub reference: String,
    pub commit: String,
}

impl GitLockEntry {
    pub fn new(source: &str, git: &GitSourceSpec, commit: impl Into<String>) -> Self {
        Self {
            source: source.to_string(),
            repo: git.repo.clone(),
            reference: git.ref_selector(),
            commit: commit.into(),
        }
    }

    /// True when this entry was recorded for the same repository and ref the
    /// source is configured with now.
    pub fn matches(&self, git: &GitSourceSpec) -> bool {
        self.repo == git.repo && self.reference == git.ref_selector()
    }
}

/// How a git source relates to the lockfile.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum GitLockStatus<'a> {
    /// No entry for this source id.
    Unlocked,
    /// An entry for the same repo and ref.
    Locked(&'a GitLockEntry),
    /// An entry exists for this source id but for another repo or ref.
    Stale(&'a GitLockEntry),
}

impl GitLockfile {
    pub fn entry_for(&self, source_id: &str) -> Option<&GitLockEntry> {
        self.git.iter().find(|entry| entry.source == source_id)
    }

    pub fn status(&self, source_id: &str, git: &GitSourceSpec) -> GitLockStatus<'_> {
        match self.entry_for(source_id) {
            None => GitLockStatus::Unlocked,
            Some(entry) if entry.matches(git) => GitLockStatus::Locked(entry),
            Some(entry) => GitLockStatus::Stale(entry),
        }
    }

    pub fn parse(contents: &str) -> Result<Self, String> {
        let lock: Self = toml::from_str(contents).map_err(|error| error.to_string())?;
        if lock.version != LOCKFILE_VERSION {
            return Err(format!(
                "unsupported lockfile version {} (expected {LOCKFILE_VERSION})",
                lock.version
            ));
        }
        Ok(lock)
    }

    /// Reads a lockfile; a missing file is `Ok(None)`.
    pub fn load(path: &Path) -> Result<Option<Self>, String> {
        match fs::read_to_string(path) {
            Ok(contents) => Self::parse(&contents)
                .map(Some)
                .map_err(|error| format!("invalid lockfile '{}': {error}", path.display())),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(None),
            Err(error) => Err(format!(
                "failed to read lockfile '{}': {error}",
                path.display()
            )),
        }
    }

    /// Deterministic TOML rendering (entries sorted by source id).
    pub fn render(&self) -> String {
        let mut entries = self.git.clone();
        entries.sort_by(|left, right| left.source.cmp(&right.source));
        let mut out = String::new();
        out.push_str("# Generated by `gaia lock`. Commit this file to pin git sources.\n");
        out.push_str("# Refresh with `gaia lock <build> --update [source-id]`.\n");
        let _ = writeln!(out, "version = {LOCKFILE_VERSION}");
        for entry in entries {
            out.push_str("\n[[git]]\n");
            let _ = writeln!(out, "source = {}", toml_string(&entry.source));
            let _ = writeln!(out, "repo = {}", toml_string(&entry.repo));
            let _ = writeln!(out, "ref = {}", toml_string(&entry.reference));
            let _ = writeln!(out, "commit = {}", toml_string(&entry.commit));
        }
        out
    }

    /// Writes the lockfile atomically.
    pub fn write(&self, path: &Path) -> Result<(), String> {
        let temp = path.with_extension("lock.tmp");
        fs::write(&temp, self.render())
            .and_then(|()| fs::rename(&temp, path))
            .map_err(|error| format!("failed to write lockfile '{}': {error}", path.display()))
    }
}

fn toml_string(value: &str) -> String {
    toml::Value::String(value.to_string()).to_string()
}

/// Lockfile path for a build entrypoint: `configs/builds/cm5.toml` locks into
/// `configs/builds/cm5.gaia.lock`.
pub fn lockfile_path_for_build_file(build_file: &Path) -> PathBuf {
    let stem = build_file
        .file_stem()
        .map(|stem| stem.to_string_lossy().into_owned())
        .unwrap_or_else(|| "build".into());
    build_file.with_file_name(format!("{stem}{LOCKFILE_SUFFIX}"))
}

/// Lockfile path for a resolved build, if it was loaded from a file.
pub fn lockfile_path(spec: &ResolvedBuildSpec) -> Option<PathBuf> {
    spec.selection
        .selected_build_file
        .as_deref()
        .map(|path| lockfile_path_for_build_file(Path::new(path)))
}

/// Applies matching lock entries to the spec's git sources. Stale entries
/// are left for validation to report.
pub fn apply_git_lockfile(spec: &mut ResolvedBuildSpec, lock: &GitLockfile) {
    for source in &mut spec.sources {
        let source_id = source.id.as_str().to_string();
        if let SourceDefinition::Git(git) = &mut source.definition
            && git.rev.is_none()
            && let GitLockStatus::Locked(entry) = lock.status(&source_id, git)
        {
            git.locked_commit = Some(entry.commit.clone());
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn git(branch: &str) -> GitSourceSpec {
        GitSourceSpec {
            repo: "https://example.invalid/orion.git".into(),
            branch: Some(branch.into()),
            tag: None,
            rev: None,
            subdir: None,
            update: false,
            refresh_policy: gaia_spec::SourceRefreshPolicySpec::Auto,
            pin_policy: gaia_spec::SourcePinPolicySpec::Locked,
            locked_commit: None,
        }
    }

    #[test]
    fn lockfile_round_trips_and_sorts_entries() {
        let lock = GitLockfile {
            version: LOCKFILE_VERSION,
            git: vec![
                GitLockEntry::new("zeta", &git("main"), "b".repeat(40)),
                GitLockEntry::new("alpha", &git("dev"), "a".repeat(40)),
            ],
        };
        let rendered = lock.render();
        assert!(rendered.find("alpha").unwrap() < rendered.find("zeta").unwrap());
        assert!(rendered.contains("ref = \"branch:dev\""));
        let parsed = GitLockfile::parse(&rendered).expect("parse");
        assert_eq!(parsed.git.len(), 2);
        assert_eq!(
            parsed.entry_for("zeta").map(|entry| entry.commit.as_str()),
            Some("b".repeat(40).as_str())
        );
    }

    #[test]
    fn status_distinguishes_locked_stale_and_unlocked() {
        let lock = GitLockfile {
            version: LOCKFILE_VERSION,
            git: vec![GitLockEntry::new("orion", &git("main"), "c".repeat(40))],
        };
        assert!(matches!(
            lock.status("orion", &git("main")),
            GitLockStatus::Locked(_)
        ));
        assert!(matches!(
            lock.status("orion", &git("release")),
            GitLockStatus::Stale(_)
        ));
        assert_eq!(lock.status("other", &git("main")), GitLockStatus::Unlocked);
    }

    #[test]
    fn lockfile_path_sits_next_to_build_entrypoint() {
        assert_eq!(
            lockfile_path_for_build_file(Path::new("/w/configs/builds/cm5.toml")),
            PathBuf::from("/w/configs/builds/cm5.gaia.lock")
        );
    }

    #[test]
    fn rejects_unknown_versions() {
        assert!(GitLockfile::parse("version = 9\n").is_err());
    }
}
